const appUrlsJson = {
  ourAppUrls: {},
  mainPortalUrls: {
    auth: {
      login: '/login',
      signup: '/signup',
    },
    dashboard: {
      patient: '/dashboard/patient',
      default: '/dashboard',
      carer: '/dashboard/carer',
      superadmin: '/rbac/overview',
      madmin: '/rbac/overview',
    },
    tracking: {
      index: '/tracking',
      goals: '/tracking/goals',
      coping: '/tracking/coping',
      diary: '/tracking/diary',
      trackers: {
        index: '/tracking/trackers',
        dashboard: '/tracking/trackers/dashboard',
        overview: '/tracking/trackers/overview',
        sleep: '/tracking/trackers/sleep',
        mood: '/tracking/trackers/mood',
        alcohol: '/tracking/trackers/alcohol',
        pain: '/tracking/trackers/pain',
        problem: '/tracking/trackers/problem',
        smoking: '/tracking/trackers/smoke',
        bloodPressure: '/tracking/trackers/blood-pressure',
        bmiWeight: '/tracking/trackers/bmi-weight',
        temperature: '/tracking/trackers/temperature',
        period: '/tracking/trackers/period',
        headache: '/tracking/trackers/headache',
        preheadache: '/tracking/trackers/preheadache',
        exercise: '/tracking/trackers/exercise',
        dailySteps: '/tracking/trackers/daily-steps',
        weight: '/tracking/trackers/weight',
        waist: '/tracking/trackers/waist-circumference',
        diet: '/tracking/trackers/diet',
        fluid: '/tracking/trackers/fluid',
      },
      fitbit: {
        fitbitSleep: '/tracking/fitbit/fitbit-sleep',
        fitbitStep: '/tracking/fitbit/fitbit-step',
        portal: '/fitbit',
      },
      deviceTracker: {
        index: '/tracking/device',
        dashboard: '/tracking/device/dashboard',
      },
    },
    profile: {
      index: '/profile',
      aboutMe: {
        personalOverview: '/profile/about-me/overview',
        personalDetails: '/profile/about-me/details',
        myBackground: '/profile/about-me/background',
        myNeeds: '/profile/about-me/needs',
        viewRecord: '/profile/about-me/record',
        consent: '/profile/about-me/consent',
        preferences: '/profile/about-me/preferences',
        deactivateAccount: '/profile/about-me/deactivateAccount',
        goals: '/profile/about-me/goal',
      },
      trusts: '/profile/trusts/management',
      trustInvites: '/profile/trusts/invites',
      keyHealthInfo: '/profile/key-health-info',
      myContacts: '/profile/key-contacts',
    },
    settings: {
      index: '/account',
      accountSettings: '/account/details',
      trustManagement: '/account/trusts/management',
      trustInvites: '/account/trusts/invites',
      viewRecord: '/account/record',
      consent: '/account/consent',
      preferences: '/account/preferences',
      deactivateAccount: '/account/deactivateAccount',
      myProfessionalProfile: '/account/my-profile',
      settings: '/account/settings',
      globalSettings: '/global/brand',
      moduleSettings: '/global/module',
      brandSettings: '/global/brand',
    },
    theme: {
      index: '/theme',
      themeSettings: '/theme/theme-settings',
    },
    superadmin: {
      adminlist: '/superadmin/admin-list',
      adminnew: '/superadmin/admin-new',
    },
    carer: {
      accessHealth: '/dashboard/carer/health-access',
    },
    admin: {
      index: '/admin',
      people: {
        myProfessionalProfile: '/admin/people/my-profile',
        directory: '/admin/people/directory',
        professionalCirclePatient: '/admin/people/professional-circle/patient',
        professionalCircleColleague:
          '/admin/people/professional-circle/colleague',
      },
      settings: {
        settings: '/admin/settings',
      },
    },
    clinician: {
      // caseLoad: {
      //   caseLoad: '/case-load',
      // },
      notifications: '/notifications-list',
      people: {
        index: '/people',
        myProfessionalProfile: '/people/my-profile',
        directory: '/people/directory',
        professionalCirclePatient: '/people/professional-circle/patient',
        professionalCircleColleague: '/people/professional-circle/colleague',
      },
      settings: {
        settings: '/settings',
      },
    },
    caseLoad: {
      index: '/caseload',
      clinician: {
        clinicalCaseload: '/caseload/clinical-caseload',
        infoHealth: '/caseload/clinical-caseload/connections/patients/health',
        infoConnect: '/caseload/clinical-caseload/connections/patients/connect',
        infoTracker: '/caseload/clinical-caseload/connections/patients/tracker',
        infoAbout: '/caseload/clinical-caseload/connections/patients/about',
      },
      admin: {
        teamCaseload: '/caseload/team-caseload',
        patientOverview: '/caseload/patient-overview',
        bestInterest: '/caseload/best-interest',
        myClinicalCaseload: '/caseload/my-clinical-caseload',
      },
    },
    myhealth: {
      index: '/my-health',
      healthOverview: '/my-health/overview',
      careJourney: '/my-health/care-journey',
      carePlans: '/my-health/care-journey/care-plans',
      advanceCarePlan: '/my-health/care-journey/advance-care-plan',
      viewCarePlan: '/my-health/care-journey/view-care-plan',
      aboutme: '/my-health/aboutme',

      // currentHealth: '/my-health/current-health',
      currentHealth: {
        diagnoses: '/my-health/current-health/diagnoses',
        allergies: '/my-health/current-health/allergies',
        medications: '/my-health/current-health/medications',
      },
      documents: '/my-health/documents/all',
      documentUpload: '/my-health/documents/document-upload',
      documentsUnread: '/my-health/documents/unread',
      documentsRead: '/my-health/documents/read',
      documentsArchive: '/my-health/documents/archive',
      documentView: '/my-health/documents/view',
      documentsLetter: '/my-health/documents/letter',
      documentsLetterView: '/my-health/documents/letter/view',
      lifeStyle: {
        myHealthFactors: '/my-health/lifestyle/my-health-factors',
        hobbiesActivities: '/my-health/lifestyle/hobbies-activities',
      },
      healthHistory: '/my-health/health-history',
      diagnosisHistory: '/my-health/health-history/diagnosis',
      medicationHistory: '/my-health/health-history/medication',
      allergiesHistory: '/my-health/health-history/allergies',
      encounters: '/my-health/consulations-events',
    },
    circle: {
      index: '/my-community',
      connectOverview: '/my-community/overview',
      serviceUser: {
        myCarers: '/my-community/my-circle/my-carers',
        myPeers: '/my-community/my-circle/my-peers',
        myClinicians: '/my-community/my-circle/my-clinicians',
        myAdmins: '/my-community/my-circle/my-admins',
        infoHealth: '/my-community/my-circle/patients/health',
        infoTracker: '/my-community/my-circle/patients/tracker',
        infoConnect: '/my-community/my-circle/patients/connect',
      },
      admin: {
        new: '/admin/my-community/my-circle/new',
        careTeam: '/admin/my-community/my-circle/care-team',
        clinicians: '/admin/my-community/my-circle/clinicians',
        patients: '/admin/my-community/my-circle/patients',
      },
      clinician: {
        patients: '/my-community/connections/patients',
        colleague: '/my-community/connections/colleagues',
        messages: '/my-community/messages',
        patientsInvite: '/my-community/connections/patients/invite',
        info: '/my-community/info',
        infoHealth: '/my-community/connections/patients/health',
        infoTracker: '/my-community/connections/patients/tracker',
        infoConnect: '/my-community/connections/patients/connect',
      },
      messages: '/my-community/messages',
      requestRecieved: '/my-community/request-recieved',
      requestSent: '/my-community/request-sent',
    },
    questionnaires: {
      clinician: {
        index: '/questionnaires',
        dashboard: '/questionnaires/dashboard',
        formsQuestionnaires: '/questionnaires/forms-questionnaires',
        formApprovals: '/questionnaires/form-approvals',
        responses: '/questionnaires/responses',
      },
    },
    resources: {
      index: '/resources',
      myResources: '/resources/my-resources',
      myResourcesAll: '/resources/my-resources/all',
      myResourcesSave: '/resources/my-resources/save',
      myResourcesRecommended: '/resources/my-resources/recommended',
      recommendedIndex: '/recommended-resources',
      allResources: '/resources/all-resources',
      recommendedResources: '/recommended-resources',
      apps: '/resources/apps',
      articles: '/resources/articles',
      events: '/resources/events',
      videos: '/resources/videos',
      tips: '/resources/tips',
      usefulLinks: '/resources/useful-links',
      researchPapers: '/resources/research-papers',
      stories: '/resources/stories',
      patientLeafLets: '/resources/patient-leaflets',
      openDialogSearch: '/resources/openDialogSearch',
      healthAZ: '/resources/health-a-z',
      hnaForms: '/resources/hna-forms',
      hciLibrary: '/resources/hci-library',
      bereavementsupport: '/resources/bereavement-support',
      viewResource: '/resources/my-resources/view-resource',
    },
    notifications: {
      index: '/notifications',
      overView: '/notifications/overview',
      createNotification: '/notifications/create-notification',
      editNotification: '/notifications/edit-notification',
      notificationsHistory: '/notifications/notifications-history',
      scheduledNotifications: '/notifications/scheduled-notifications',
      templates: '/notifications/templates',
      activityLog: '/notifications/activityLog',
      patientNotifications: '/notifications/all',
      notificationPreferences: '/notifications/preferences',
      smsOverview: '/notifications/sms/overview',
      smsTemplate: '/notifications/sms/templates',
      addSms: '/notifications/sms/overview/add',
      smsTemplateAll: '/notifications/sms/templates',
      smsTemplateActive: '/notifications/sms/templates/active',
      smsTemplateInactive: '/notifications/sms/templates/inactive',
      smsTemplateArchived: '/notifications/sms/templates/archived',
      createSmsTemplate: '/notifications/sms/templates/add',
      smsScheduled: '/notifications/scheduled-notifications/sms',
      smsViewScheduled: '/notifications/scheduled-notifications/view',
      smsNotificationsHistory: '/notifications/notifications-history/sms',
      smsNotificationsHistoryView: '/notifications/notifications-history/view',
    },
    appointment: {
      index: '/appointment',
      admin: {
        allClinicLocations: '/appointment/location',
        ClinicLocationsDetails: '/appointment/location/clinic',
        addClinic: '/appointment/location/add-clinic',
        editClinic: '/appointment/location/edit-clinic',
        dashboard: '/appointment/dashboard',
        allClinics: '/appointment/clinics',
        addClinicPage: '/appointment/clinics/add',
        allClinicsPatient: '/appointment/clinics/clinic-patient',
        cliniciansGroups: '/appointment/clinicians-groups',
        vaccinationType: '/appointment/vaccination',
        createVaccination: '/appointment/vaccination/create',
        amendBooking: '/appointment/amend',
        amendBookingConsultation: '/appointment/amend/consultation',
        amendBookingVaccination: '/appointment/amend/vaccination',
        patients: '/appointment/patients',
        diagnosisType: '/appointment/diagnosis',
        diagnosisTypeCreate: '/appointment/diagnosis/create',
        appointmentType: '/appointment/type',
        appointmentTypeCreate: '/appointment/type/create',
      },
      patient: {
        index: '/my-health/appointment',
        dashboard: '/my-health/appointment/overview',
        upcomingAppointment: '/my-health/appointment/overview/upcoming',
        pastAppointment: '/my-health/appointment/overview/past',
        cancelledAppointment: '/my-health/appointment/overview/cancelled',
        appointmentDetails:
          '/my-health/appointment/overview/appointment-details',
        appointmentBooking: '/my-health/appointment/booking',
        viewVaccinationBooking:
          '/my-health/appointment/view-vaccination-booking',
        rioReschedule: '/my-health/appointment/overview/rio-reschedule',
      },
      clinician: {
        dashboard: '/appointment/dashboard',
        newClinic: '/appointment/myclinics',
        addClinic: '/appointment/myclinics/add',
        requestDiagnosis: '/appointment/myclinics/request-diagnosis',
        todaysClinic: '/appointment/all-clinics/today',
        upcomingClinic: '/appointment/all-clinics/upcoming-clinic',
        pastClinic: '/appointment/all-clinics/past-clinic',
        patients: '/appointment/patients',
        allAppointment: '/appointment/patients/all-appointment',
      },
    },
    rbac: {
      index: '/rbac',
      superAdmin: {
        dashboard: '/rbac/overview',
        overview: '/rbac/trust/overview',
        modules: '/rbac/modules',
        userManagement: '/rbac/user-management/all-user/active-user',
        archivedUser: '/rbac/user-management/all-user/archived-user',
        inactiveUser: '/rbac/user-management/all-user/inactive-user',
        inviteUser: '/rbac/user-management/invite-user',
        permissionManagement: '/rbac/permission-management/user-role/admin',
        adminActiveUser: '/rbac/permission-management/active-user/admin',
        superAdminActiveUser:
          '/rbac/permission-management/active-user/trust-admin',
        clinicianActiveUser:
          '/rbac/permission-management/active-user/clinician',
        patientActiveUser: '/rbac/permission-management/active-user/patient',
        ClinicianPermissioManagement:
          '/rbac/permission-management/user-role/clinician',
        superAdminPermissioManagement:
          '/rbac/permission-management/user-role/trust-admin',
        PatientPermissionManagement:
          '/rbac/permission-management/user-role/patient',
        adminSubrolePermission: '/rbac/permission-management/sub-role/admin',
        clinicianSubrolePermission:
          '/rbac/permission-management/sub-role/clinician',
        patientSubrolePermission:
          '/rbac/permission-management/sub-role/patient',
        createSubrolePermission: '/rbac/permission-management/sub-role/create',
        userGroup: '/rbac/user-group',
        portalUsers: '/rbac/user-management/portal-users',
        systemUsers: '/rbac/system-users',
        branding: '/rbac/branding',
        termsAndPrivacy: '/rbac/terms',
        subRoles: '/rbac/user-management/sub-roles',
        createSubroles: '/rbac/user-management/sub-roles/create',
        archiveUserInfo:
          '/rbac/user-management/all-user/active-user/pending-task',
        deleteUserInfo:
          '/rbac/user-management/all-user/active-user/delete-pending-task',
      },
      mediwaveAdmin: {
        dashboard: '/rbac/overview',
        modules: '/rbac/modules-admin',
        branding: '/rbac/branding-admin',
        regional: '/rbac/regional',
        regionalAdd: '/rbac/regional/add',
        Add: '/rbac/regional/add',
        regionalManageModules: '/rbac/regional/managearea/modules',
        regionalManageInformation: '/rbac/regional/managearea/information',
        regionalManageRoles: '/rbac/regional/managearea/roles',
        regionalManageRolesAdd: '/rbac/regional/managearea/roles/add',
        regionalManageAllUsers: '/rbac/regional/managearea/allusers',
        regionalManageAllUsersAdd: '/rbac/regional/managearea/allusers/add',
        emailConfiguration: '/rbac/regional/managearea/emailconfiguration',
        serviceOverview: '/rbac/regional/service/overview',
        serviceManageInformation: '/rbac/regional/manage/service/information',
        serviceManageAllUsers: '/rbac/regional/manage/service/allusers',
        serviceManageAllUsersAdd: '/rbac/regional/manage/service/allusers/add',
        serviceAdd: '/rbac/regional/manage/overview/service/add',
        trusts: '/rbac/trusts',
        trustsDetails: '/rbac/trusts/details',
        trustsManage: '/rbac/trusts/manage',
        trustAdd: '/rbac/trusts/add',
        trustsUrgentHelp: '/rbac/trusts/emergency-help',
      },
      regionalAdmin: {
        index: '/regional',
        regional: '/regional',
        dashboard: '/regional/overview',
        regionalManageModules: '/regional/managearea/modules',
        regionalManageInformation: '/regional/managearea/information',
        regionalManageRoles: '/regional/managearea/roles',
        regionalManageRolesAdd: '/regional/managearea/roles/add',
        regionalManageAllUsers: '/regional/usermanagement/allusers',
        regionalManageAllUsersAdd: '/regional/usermanagement/allusers/add',
        emailConfiguration: '/regional/managearea/emailconfiguration',
        serviceOverview: '/regional/service/overview',
        serviceManageInformation: '/regional/manage/service/information',
        serviceManageAllUsers: '/regional/manage/service/allusers',
        serviceManageAllUsersAdd: '/regional/manage/service/allusers/add',
        serviceAdd: '/regional/manage/service/add',
      },
    },
    patient: {
      index: '/patientnotification',
      patientNotifications: '/patientnotification/message',
    },
    messages: {
      inbox: '/messages/inbox',
      sent: '/messages/sent',
      newMessage: '/messages/new-message',
      messageThread: '/messages/thread',
    },
    // !! dont use !!
    nhsappold: {
      index: '/nhs',
      viewAppointment: '/nhs/view-appointment',
      appointmentOverview: '/nhs/overview',
      bookingAppointment: '/nhs/bookingappointment',
      chooseAppointment: '/nhs//bookingappointment/chooseappointment',
      selectClinic: '/nhs//bookingappointment/selectclinic',
      appointmentforRefferal: '/nhs//bookingappointment/appointmentforrefferal',
      appointmentBooked: '/nhs//bookingappointment/appointmentbooked',
      manageAppointment: '/nhs/manageappointment',
      nhsTerms: '/nhs/manageappointment/nhsterms',
      rescheduleAppointment: '/nhs/rescheduleappointment',
      askReschedule: '/nhs/rescheduleappointment/askreschedule',
      askCancelation: '/nhs/cancelappointment/askcancelation',
      startReschedule: '/nhs/rescheduleappointment/startreschedule',
      reasonforReschedule: '/nhs/rescheduleappointment/reasonforreschedule',
      reviewRequest: '/nhs/rescheduleappointment/reviewrequest',
      appointmentRechedule: '/nhs/rescheduleappointment/appointmentrechedule',
      cancelAppointment: '/nhs/cancelappointment',
      appointmentCancelled: '/nhs/cancelappointment/appointmentcancelled',
    },
    nhsapp: {
      index: '/p',
      viewOneAppointment: '/p/:trustCode/appointments/:uuid',
      requestAppointment: '/p/:trustCode/appointments/:uuid/request/:action',
      cancel: {
        preparation: '/p/:trustCode/appointments/:uuid/cancel/prepare',
        reason: '/p/:trustCode/appointments/:uuid/cancel/reason',
        review: '/p/:trustCode/appointments/:uuid/cancel/review',
        confirmation: '/p/:trustCode/appointments/:uuid/cancel/confirmation',
      },
      reschedule: {
        preparation: '/p/:trustCode/appointments/:uuid/reschedule/prepare',
        new_date: '/p/:trustCode/appointments/:uuid/reschedule/new-date',
        reason: '/p/:trustCode/appointments/:uuid/reschedule/reason',
        review: '/p/:trustCode/appointments/:uuid/reschedule/review',
        confirmation:
          '/p/:trustCode/appointments/:uuid/reschedule/confirmation',
      },
    },
    referral: {
      index: '/referral',
      patient: {
        referralOverview: '/referral',
        pending: '/referral/pending',
        draft: '/referral/draft',
        submitted: '/referral/submit',
      },
      admin: {
        referralAdmin: '/referral/admin',
        archivedReferral: '/referral/archive',
        serviceAdmin: '/referral/service',
      },
    },
  },
  outerDomainUrls: {},
};

function checkInnerJson(jsonData: any) {
  if (jsonData) {
    for (const key in jsonData) {
      if (typeof jsonData[key] === 'string') {
        jsonData[key] = `${jsonData[key]}`;
      } else {
        jsonData[key] = checkInnerJson(jsonData[key]);
      }
    }
  }
  return jsonData as typeof appUrlsJson.ourAppUrls;
}

export const portalUrls = {
  ...checkInnerJson(appUrlsJson.ourAppUrls),
  outerDomainUrls: appUrlsJson.outerDomainUrls,
  mainPortalUrls: appUrlsJson.mainPortalUrls,
};

export default portalUrls;
